import { AppHeader } from "../chrome";
import { Button, Callout } from "../ui";

/**
 * Stage content shown while a verified problem is being generated. Pure CSS
 * pulse (compositor-only) so it stays smooth at 60fps. Lives inside the shell,
 * so the header stats stay put between problems.
 */
export function PracticeLoading() {
  return (
    <div
      className="flex flex-col items-center gap-6 px-4 py-6"
      aria-busy="true"
      aria-live="polite"
    >
      {/* A skeleton shaped like a real problem (prompt · figure · answer grid),
          so the swap to the live problem has no layout jump. Purely decorative. */}
      <div
        aria-hidden
        className="flex w-full max-w-md flex-col items-center gap-6"
      >
        <div className="h-6 w-3/4 animate-pulse rounded-full bg-default motion-reduce:animate-none" />
        <div className="h-40 w-full max-w-[16rem] animate-pulse rounded-3xl bg-default motion-reduce:animate-none" />
        <div className="grid w-full grid-cols-2 gap-3">
          {Array.from({ length: 4 }).map((_, i) => (
            <div
              key={i}
              className="h-14 animate-pulse rounded-2xl bg-default motion-reduce:animate-none"
            />
          ))}
        </div>
      </div>
      <p className="text-sm font-medium text-muted">Generating a fresh problem…</p>
    </div>
  );
}

/**
 * Stage content when no candidate passed verification (e.g. the backend is
 * unavailable). The retry / exit actions live in the shell footer supplied by
 * the session. Per P4 we'd rather show this than an unverified problem.
 */
export function PracticeError() {
  return (
    <div className="mx-auto flex max-w-md flex-col items-center gap-4 px-4 py-10 text-center">
      <Callout
        intent="warning"
        title="No verified problem right now"
        icon={<ShieldIcon />}
      >
        We couldn't generate a problem that passed verification. Practice only
        ever shows checked problems, so nothing wrong slips through — give it
        another try in a moment.
      </Callout>
    </div>
  );
}

/** A shield-check mark — reinforces that practice only serves verified problems. */
function ShieldIcon() {
  return (
    <svg aria-hidden="true" className="size-4" viewBox="0 0 16 16">
      <path
        d="M8 1.5 13 3.2v4.1c0 3.2-2.1 5.6-5 6.7-2.9-1.1-5-3.5-5-6.7V3.2L8 1.5Zm2.7 4.2-3.4 3.4-1.6-1.6-1 1 2.6 2.6 4.4-4.4-1-1Z"
        fill="currentColor"
      />
    </svg>
  );
}

/**
 * Full-screen state for the AI-off path (`VITE_AI_ENABLED` ≠ "true"). Infinite
 * Practice is the one surface that genuinely needs generation, so with AI off it
 * degrades to this graceful explainer (P1) — the rest of the app is unaffected
 * and still teaches end-to-end.
 */
export function PracticeUnavailable({ onBack }: { onBack: () => void }) {
  return (
    <div className="min-h-svh bg-background text-foreground">
      <AppHeader />
      <main className="practice-stage-in mx-auto flex max-w-lg flex-col items-center gap-6 px-4 py-16 text-center sm:py-24">
        <h1 className="text-2xl font-bold tracking-tight">Infinite Practice</h1>
        <Callout intent="info" title="Practice requires AI">
          Infinite Practice serves an endless stream of fresh, verified problems
          generated by AI. It's turned off right now, so this mode is
          unavailable — but the full course still teaches end-to-end.
        </Callout>
        <Button variant="accent" size="lg" onPress={onBack}>
          Back to course
        </Button>
      </main>
    </div>
  );
}
